### ISSUE TITLE
Create a readme file

### ISSUE THREAD

**Issue by apurvjha123** [Chit-Chat-Org/chit-chat-nextjs#12]
As you can see readme file is missing in this repo.

Add a README.md which show what it does, how to install locally and mention the reference.

you can create readme ` https://readme.so/` from here 

take reference of readme file from here https://github.com/Chit-Chat-Org/Chit-Chat

**Comment by PuR-vI** [comment]
Sure, i would like to add a descriptive README.md file to this. Please assign this to me

**Comment by soumojeet-mondal** [comment]
Since the issue hasn't been yet been solved
I am Working on this Issue! Please assign me this to me
