### ISSUE TITLE
Dockerize Project and Set Up CI/CD Pipelines

### ISSUE THREAD

**Issue by Ayush41** [Chit-Chat-Org/chit-chat-nextjs#53]
Hello,

I noticed that the project is not currently dockerized and does not utilize GitHub Actions for CI/CD. Additionally, the site appears to be down with the following error: "Hmmm… can't reach this page. Check if there is a typo in chit-chat.tech."

I would like to propose the following improvements:
1. **Dockerization**: Containerize the application using Docker to ensure consistent environments and simplify deployment.
2. **CI/CD Pipelines**: Set up GitHub Actions for continuous integration and continuous deployment to automate testing and deployment processes.

I have experience in both Docker and CI/CD and would be happy to contribute to the project by implementing these changes. Please let me know if you would be interested in this contribution.

**Comment by apurvjha123** [comment]
Hello Ayush,  

The website has undergone a massive UI overhaul, and the link has changed to https://chit-chat.fun/. You can check it out now!  

We are not using GitHub Actions for CI/CD anymore and have Dockerized the application for smoother deployment and consistency.  

Feel free to explore the updated site and share any suggestions or feedback. We’d be more than happy to hear from you!  

Best regards,  
Apurv Jha

**Comment by Ayush41** [comment]
Hello Apurv,

Thank you for the update! I appreciate the information about the new link and the changes to the deployment process.

I'll check out the updated site at [chit-chat.fun](https://chit-chat.fun/) and explore the new UI. It's great to hear that the application is now Dockerized for smoother deployment.

Could you please let me know which platform you are using now instead of GitHub Actions for CI/CD? If I have any suggestions or feedback, I'll be sure to share them with you.

Best regards,  
Ayush
